### ISSUE TITLE
Design Schema service

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/general-issues#114]
Schema service will provide Ember UI with a set of schemas from which the UI could build and display metadata forms. THe order of the schema to be displayed should be somehow indicated by the service.

**Comment by birkland** [comment]
https://docs.google.com/document/d/1Ki6HUYsEkKPduungp5gHmr7T_YrQUiaTipjorcSnf4s/edit#

**Comment by htpvu** [comment]
done
