### ISSUE TITLE
Hash a plan and design for Journal service

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/general-issues#118]
Journal service should be a backend service. It should provide the following functionalities:
- given an ISSN  & pubtype, return the journal object with matching ISSN
- given an ISSN & pubtype , if no journal is found with matching ISSN, *create* a new journal object in the PASS repo and return the new created object
- given an ISSN & additional information about a journal, update issn-mathching journal object with new information.

Expected user of this service will be the ember UI. The UI will get ISSN and pubtype from DOI-crossref look up.

Before implementing this service, please hash out a design and steps for implementation with associated estimate.  sample steps include:
- set up github projects & skeleton code
- design & propose interface (in form of PRs for review)
- implementation of the interface
- dockerization
- integrating with existing components
etc

**Comment by htpvu** [comment]
Design & tasks breakdown doc https://docs.google.com/document/d/1l_esI2M1arH8OIZqLcADTolralAcydLR4x5H1yjWlP4/edit?ts=5c7973e3

**Comment by jrmartino** [comment]
design and plan complete
