### ISSUE TITLE
Design a policy engine

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/general-issues#120]
Given information about a user, his/her grant, and content being deposited, the policy engine will determine which repositories is applicable to a submission and of those repositories, which are optional, which required. 

input/output diagram https://www.lucidchart.com/invitations/accept/d9d7578c-c256-452b-b85d-64a746aff045

The outcome of this ticket should include the following: 
- design & interface of the policy engine 
- list of implementation tasks to implement the engine's design
- requirements for data model (new and updates)
- rough/initial description of how the engine could be used by the ember UI.

**Comment by emetsger** [comment]
Design document url: https://docs.google.com/document/d/1XqVt8vZakhTsAt6SMD4nCGlOeRfwOGHw4tJv8eReV4c/edit?usp=sharing

**Comment by emetsger** [comment]
Implementation document url:
https://docs.google.com/document/d/1v-76bYyNcgi6yBnNrisdtgM-MzA1l03piuU4SAFBcRY/edit

**Comment by htpvu** [comment]
High level design is complete. Further analysis on how to handle the implementaiton of policy logic will be done an a separate card at the beginning of the implementation phase.
