### ISSUE TITLE
analyze and propose solution on how to implement and enforce each policy in terms of repositories and their requiredness

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/general-issues#123]
Fill in the design gap left open after the high level design of Policy Service. Specifically, design a way through which individual policy's business logic can be encoded and executed. 

Ideally the solution would allow for a new policy to be added via means of data augmentation or configuration rather than coding new implementation.

**Comment by birkland** [comment]
I believe this has been satisfied by the concrete design and DSL plan https://docs.google.com/document/d/1cPNN9TFUCLX-4yVoRuhmM0Vcrh3WYWNs-rwAszuJWXk/edit
