### ISSUE TITLE
Update CMF workflow diagram to reflect what's been implemented

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/general-issues#131]
https://www.lucidchart.com/invitations/accept/f565602c-7fa0-4f2b-b001-41836938a803

**Comment by emetsger** [comment]
See updated document: https://www.lucidchart.com/documents/edit/d397f6a3-16a2-4277-9101-8d7e077e9f45/0

If the updated document makes sense to reviewers, this issue can be closed.

**Comment by htpvu** [comment]
this looks good good to me. made a copy of it to put in the DRCC own-ed lucid chart space.
