### ISSUE TITLE
Create an assets image containing Harvard data to facilitate local testing

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/general-issues#133]
Bootstrap instruction - not sure how update it is. https://docs.google.com/document/d/1CaMa_NbYPxj29gu-PjKv7kym4Ltoceg-eVKXh4npcF4/edit

at the end, I think the assets image needs to contain:
grants, funders, journals, submissions, users, repositories, policies, schemas. All are specific to harvard, except for Journals.

**Comment by jrmartino** [comment]
i found the loader jar `fcrepo-import-export-0.3.0-SNAPSHOT.jar`, but have not been successful at locating the `everything` data set

**Comment by jrmartino** [comment]
so, some questions/comments - this process will only be useful in the Harvard case for those things which are in common with the JHU case - so probably just the Journals, for which we can just use the journal loader.  

taking inventory:
grants, funders, and users will come from the data provided by Harvard
journals - from our journal loader (PMC and Medline)
submissions - ?
repositories - we will need a description for Harvard's IR - will we also direct deposits to PMC?
policies - create new ones for Harvard policy/policies - weill we need existing NIH policies as well?
schemas - ?

**Comment by htpvu** [comment]
this is done, resulting asset image is par tof this PR https://github.com/OA-PASS/pass-docker/pull/236
