### ISSUE TITLE
Update the Repository and Policy object in Harvard's asset image to reflect the text with paragraph breaks and hyper links

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/general-issues#138]
See this doc for details https://docs.google.com/document/d/1nepZM2rC6FbkH7r3JDkgsIg27_4ca6s9YQyu9of-YNg/edit

Please be sure to capture the hyper links as well as paragraph breaks as described.

**Comment by jrmartino** [comment]
this is complete
