### ISSUE TITLE
When clicked on invitation link sent by notification service to approve a proxy submission, user encountered spinning web page 

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/general-issues#144]
a lot of troubleshooting had taken place for this behavior, the issue boils down to this:
- when a user is required to go through authentication, one of the services involved in this process fails to encode the URL properly. 
- this cases ember app to munch the URL of the submission (by dropping one of the url's slashes) and therefore it cannot load. 

fixes can are considered in two different places: 
- updating Ember to explicitly NOT dropped the slash ( this was chosen as a short term, quick fix solution)
- update one of the services involved in encoding and decoding submission URL as user goes through the authentication process: Though a more robust fix, this is more involved, and requires more thoughts and consideration. We can/probaly will revisit this approach after we put out some active fires.

**Comment by jaredgalanis** [comment]
Closed by: https://github.com/OA-PASS/pass-ember/pull/1087 AND https://github.com/OA-PASS/pass-docker/pull/248

**Comment by htpvu** [comment]
deployed via ticket ticket to DEMO and PROD https://jhulibraries.atlassian.net/browse/OPS-1189
