### ISSUE TITLE
REtroactively correct values for submitter field in PASS production repo

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/general-issues#146]
as a result of bug documented in this ticket https://github.com/OA-PASS/general-issues/issues/142, some submission has the wrong value of its submitter name and email. 

We need to find affected records and clean up this data in PASS production

**Comment by htpvu** [comment]
THis query can be ran in Production to find the submission with "corrupted" `submitterEmail` field. `https://pass.jhu.edu/es/?q=@type:Submission+submitterEmail:*submissions*&default_operator=AND&pretty`

for each of the submissions returned, we need to null out the submitterEmail.

**Comment by emetsger** [comment]
All submission resources from the above query have had the `submitterEmail` nulled out.

**Comment by emetsger** [comment]
Submission resources ending with the following UUID fragments were modified:
02240d2b56a2
16a9e2f5c979
24a4c44c559a
37ba84e25cb5
52e704d185c1
77aeb1d18ddf
85333fd12967
9f355651de8e
b0bd8562d0de
b5660732bb4b
f2e8aacc986b
