### ISSUE TITLE
Perform data update neccessary to push a COVID submission through to PASS

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/general-issues#147]
This submission is stuck in PASS to due lack of deposit agreement when the UI hung on the user trying to submit. https://pass.jhu.edu/fcrepo/rest/submissions/e4/cc/71/da/e4cc71da-7321-4914-a880-a57dd9b4dc33

Please update the submission's resource to enable it to be picked up and processed by the deposit service. 

the necessary updates to the data include: 
- [x] Attachment of deposit agreement to the metadata blob
- [x] Flip `submissionStatus` attribute of the submission resource  to `submitted`
- [x] Flip `submitted` attribute of the submission resource to `true`

Text for the deposit agreement is forth coming.

**Comment by htpvu** [comment]
Sample properly formed metadata blob could be taken from this submisison in demo: https://demo.pass.library.jhu.edu/fcrepo/rest/submissions/04/32/13/31/04321331-9ac2-4759-9c3a-ebb2dc642621

**Comment by emetsger** [comment]
Submission went through!  See https://jscholarship.library.jhu.edu/handle/1774.2/62387
