### ISSUE TITLE
Analyze the requirements for link generation service and design a plan for its implementation as it relates to the Proxy Submitter usecase 

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/general-issues#15]
expected outcomes:

- A description the need that notification service is trying to address at this use case
- enumerate its components and specify its interaction with existing components in PASS (what resources does it act on, using which criteria, how does it communicate with other things)
- enumerate list of tasks that will need to be done in order to implement this tool

**Comment by birkland** [comment]
https://docs.google.com/document/d/11tlJC8KwQ9e5C3pu3rARtxmVJz6lUJB865fm1JAHV7U/edit#heading=h.hp4r7jjj27ew
