### ISSUE TITLE
Investigate the cause of duplicated data in TEST & PROD instance

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/general-issues#156]

**Comment by jabrah** [comment]
I haven't been able to identify specific log messages that illustrate when duplicates are created, but the only mechanism I know about right now is when the loaders run with an Elasticsearch index in a bad state. Almost all of the known duplicates were created on a date that the loaders had run.

If there is an unknown pathway that can create duplicate entities, then running duplicate remediation and addressing the issues we have with logging will go a long way to making future identification easier.
