### ISSUE TITLE
Ensure all code repositories include an Apache 2.0 LICENSE file

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/general-issues#159]
Ensure all code repositories include an Apache 2.0 LICENSE file prior to moving to EF GH

**Comment by jrmartino** [comment]
Many of our repositories  contain a NOTICE.txt file which announces that the project isusing the Apache License 2.0, and has a pointer to  http://www.apache.org/licenses/LICENSE-2.0

Is this sufficient, or do we want to actually put a copy of the license in there as well?

**Comment by jrmartino** [comment]
All pass code repositories haev been updated to have both a LICENSE file and a NOTiCE file, with the exception of the `pass-http-cgi` repo which has been archived and so is not editable.
