### ISSUE TITLE
Scan all PASS repos for sensitive information in the current codebase and its history

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/general-issues#184]
Record assessment in relevant column in this list https://docs.google.com/spreadsheets/d/1Zz0GQy64Sj0-LJjSGd63hMcqJ8LJVe1WLskUg8Bh5_8/edit#gid=0

The following information is deemed sensitive:
- Internal personal id
- Internal DNS and IP addresses
- Log in credential
- Secrets files

**Comment by jrmartino** [comment]
the only sensitive info i was able to find were secrets files, encrypted settings files, and the use of the assets image.

**Comment by jrmartino** [comment]
closing issue
