### ISSUE TITLE
Evaluate need for reindexing after database updates to perform model change

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/general-issues#19]
When applying the model changes to `oapass/indexer`, it was highlighted that there may be a need for re-indexing after the model update utility is run against the live database. It is not yet clear whether the index will be correctly updated as the records are processed by the update utility, or whether the model changes will cause problems that will require a re-index.

For more information on this, see @markpatton's comment here:
https://github.com/OA-PASS/pass-indexer/pull/13#issuecomment-418725975

**Comment by htpvu** [comment]
Close in favor of a more updated ticket https://github.com/OA-PASS/general-issues/issues/31
