### ISSUE TITLE
Update demo repo to replace repository uri place holder with real uri values

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/general-issues#26]

**Comment by derekbelrose** [comment]
@htpvu can you please elaborate on this issue?  I do not know what you mean and there is no description to this issue.

**Comment by htpvu** [comment]
There are 1074 submission records in demo instance that has `https://localhost:8080/fcrepo/rest/repositories/aaa/bbb/ccc` as uris for their repositories. 

we need to update these to have proper uris for the repositories.   https://demo.pass.library.jhu.edu/es/?q=@type:Submission+repositories:%22https://demo.pass.library.jhu.edu/fcrepo/rest/repositories/aaa/bbb/ccc%22&pretty&default_operator=AND&sort=submittedDate:desc

**Comment by derekbelrose** [comment]
I do not have the knowledge of fixing this.  Aaron and/or Karen fixed this issue last time.  It would be good to bring them in on this issue.

**Comment by birkland** [comment]
Done

Deleted this many submissions: 831
Updated this many submissions: 243
Deleted this many repoCopies: 500
