### ISSUE TITLE
COEUS grant loader fails  in demo env. due to duplication of some records

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/general-issues#27]
Troubleshoot and address this issue.

**Comment by derekbelrose** [comment]
There's no need to troubleshoot, we already know the reason that it fails.  There are duplicate records in Elasticsearch for some Users and so far, one Funder.  

I am working with Aaron to clear up these issues.  I am working on a way to force close the ssh tunnel until we can split these two functions (harvesting and loading) into two functions that can be run on separate servers.  This way, the harvesting can be done inside the University network as required and the loader can be run inside the AWS network, as required.  This will eliminate the need for the fragile ssh tunnel.

**Comment by htpvu** [comment]
I believe we don't know yet why/how these duplicated records are created. 

That said, this issue can be considered resolved when the issue is addressed and the grant loader in both demo and production are back to running daily.

**Comment by derekbelrose** [comment]
That's correct, we don't know why.  All signs point to this ssh tunnel but we may never know.  This seems to be reaching back all the way to early august.

We, most definitely, do not keep logs of coeus runs that long.  It's not integrated into the AWS logging infrastructure.

**Comment by derekbelrose** [comment]
I have redesigned the way that we run this at night.  It has been running two nights in a row without issue.  At this point, I believe it's safe to close this.

It'll be nice to be able to break this out in the future.
