### ISSUE TITLE
Pruning demo account submissions

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/general-issues#30]
the following submissions need to be pruned:

https://demo.pass.library.jhu.edu/app/submissions/https:%2F%2Fdemo.pass.library.jhu.edu%2Ffcrepo%2Frest%2Fsubmissions%2Fe6%2Fc0%2Fc4%2F0a%2Fe6c0c40a-d56e-4813-a39c-a48f4b7921bd
 
https://demo.pass.library.jhu.edu/app/submissions/https:%2F%2Fdemo.pass.library.jhu.edu%2Ffcrepo%2Frest%2Fsubmissions%2F1b%2Fe2%2Fa9%2F0b%2F1be2a90b-69d9-452a-8549-9e95e097052f
 
https://demo.pass.library.jhu.edu/app/submissions/https:%2F%2Fdemo.pass.library.jhu.edu%2Ffcrepo%2Frest%2Fsubmissions%2F5d%2F27%2Fab%2F2a%2F5d27ab2a-76af-4800-89e8-cc125d3ba997
  
https://demo.pass.library.jhu.edu/app/submissions/https:%2F%2Fdemo.pass.library.jhu.edu%2Ffcrepo%2Frest%2Fsubmissions%2F8d%2F9d%2Fa7%2F45%2F8d9da745-e7fc-401b-a9ea-5360697c0a5f
 
https://demo.pass.library.jhu.edu/app/submissions/https:%2F%2Fdemo.pass.library.jhu.edu%2Ffcrepo%2Frest%2Fsubmissions%2Ffc%2F7d%2Fca%2F3a%2Ffc7dca3a-1ac8-4cea-b8de-c4b66bd3aac7

**Comment by karenhanson** [comment]
Will close once I have confirmation that this done
