### ISSUE TITLE
Evaluate the need to update indexer and design a reindexer to support new usecases and requirements

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/general-issues#31]
Requirements for autocompletions and description of data model updates are described here https://docs.google.com/document/d/1BgiveeB8ZeGcEyjbCBB2Gnl1cD7vBjfHMrZrYkxQ5O0/edit#heading=h.x9tx6lqcwfl9

Please review the documents and provide a plan (with tasks) to bring the indexer and existing data up to date with new requirements and data model.

**Comment by markpatton** [comment]
Updated with a proposal for a reindexing tool.
