### ISSUE TITLE
Additional submissions to prune

### ISSUE THREAD

**Issue by sayeedmd** [OA-PASS/general-issues#32]
@htpvu 

https://demo.pass.library.jhu.edu/app/submissions/https:%2F%2Fdemo.pass.library.jhu.edu%2Ffcrepo%2Frest%2Fsubmissions%2F7d%2F2c%2F6b%2F27%2F7d2c6b27-991a-42b4-ae1b-0ef5ac0f470e

https://demo.pass.library.jhu.edu/app/submissions/https:%2F%2Fdemo.pass.library.jhu.edu%2Ffcrepo%2Frest%2Fsubmissions%2F2f%2Fc3%2Fea%2Fa1%2F2fc3eaa1-8a3f-41c1-b9fc-63c7e050aaf7

https://demo.pass.library.jhu.edu/app/submissions/https:%2F%2Fdemo.pass.library.jhu.edu%2Ffcrepo%2Frest%2Fsubmissions%2Fea%2F21%2F1b%2F06%2Fea211b06-16c6-4ecd-9d0c-f513beee6d05

https://demo.pass.library.jhu.edu/app/submissions/https:%2F%2Fdemo.pass.library.jhu.edu%2Ffcrepo%2Frest%2Fsubmissions%2Ff5%2F68%2Ffa%2Fc7%2Ff568fac7-092e-4c33-8337-54c60e451f19

https://demo.pass.library.jhu.edu/app/submissions/https:%2F%2Fdemo.pass.library.jhu.edu%2Ffcrepo%2Frest%2Fsubmissions%2F74%2F11%2F08%2Ffa%2F741108fa-926f-46f6-ad88-75cbcc23ba9c

**Comment by karenhanson** [comment]
I have deleted these, will close when @sayeedmd can confirm through demo UI

**Comment by sayeedmd** [comment]
Confirmed. Thanks.
