### ISSUE TITLE
Deploy new J10P metadata features to demo instance for testing

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/general-issues#33]
@derekbelrose, When the ember image is ready (the image tag is available), please push this image to demo instance. 

Please coordinate with @karenhanson in timing to make sure that the demo data is updated immediately after the image push. 

Changes of the ember image and the data have to go in together for things to work properly. 

I'll update the ticket with the image tag once it's available.

**Comment by htpvu** [comment]
Tag of image to be deployed is `OA-PASS/ember: 20181011-775220d`

**Comment by karenhanson** [comment]
Deployed!
