### ISSUE TITLE
Test ember bug fix and push through to Production deployment

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/general-issues#42]
In reference of this bug https://github.com/OA-PASS/pass-ember/issues/746

the fix has been merged to `pass-ember/develop` 
--> test in pass-docker
--> if succeed, create an image --> pushed to docker hub
--> create ticket for deployment in demo (provide image tag in the ticket)
--> test in demo
--> if succeed, create ticket for deployment in production (provide image tag in the ticket)

Ideally we need to push this to production tonight. 

Test scenarios include: 
- submit submissions with DOI -->  verify that submission is successful to j10p, status and link to repo copy are populated in the submission record, Metadata records are populated  in the dspace record of the submission.
- submit submissions without DOI --> make sure metadata like publication date, publishers, authors and abstract can be added on the form. --> make sure that J10P metadata form requires at least one author's name --> verify that submission is successful to j10p, status and link to repo copy are populated in the submission record. Metadata records are populated  in the dspace record of the submission.
- submit missions without DOI, leave authors field blank in common form, enter author info in the j10p form  --> verify that submission is successful to j10p, status and link to repo copy are populated in the submission record. Metadata records are populated  in the dspace record of the submission.

resolves https://github.com/OA-PASS/pass-ember/issues/746

**Comment by karenhanson** [comment]
deployed in demo and production
