### ISSUE TITLE
Deploy new Deposit Service image to demo and production

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/general-issues#46]
Image tag: `oapass/deposit-services:0.0.9-2.3-1`

**Comment by derekbelrose** [comment]
Any new environment variables?

**Comment by htpvu** [comment]
@derekbelrose no new env vars.

**Comment by derekbelrose** [comment]
updating demo at this moment.

**Comment by derekbelrose** [comment]
demo has been updated.

**Comment by derekbelrose** [comment]
Updating production environment now
