### ISSUE TITLE
Pruning submissions in Demo instance

### ISSUE THREAD

**Issue by sayeedmd** [OA-PASS/general-issues#48]
I have a high-profile PASS talk next week at the AAU/APLU workshop on Monday, October 29th. I'll be using screenshots instead of doing a live demo but I need to prune my submissions screen. Could someone please remove the following submissions:

https://demo.pass.library.jhu.edu/app/submissions/https:%2F%2Fdemo.pass.library.jhu.edu%2Ffcrepo%2Frest%2Fsubmissions%2F7f%2Fc6%2Fff%2Fdd%2F7fc6ffdd-2529-4d3c-a365-991eee0e4170

https://demo.pass.library.jhu.edu/app/submissions/https:%2F%2Fdemo.pass.library.jhu.edu%2Ffcrepo%2Frest%2Fsubmissions%2F97%2Ffd%2Fe3%2F36%2F97fde336-bba5-40dc-8b1e-e695cfab3593

@htpvu

**Comment by sayeedmd** [comment]
Thanks. It turns out I have 5 minutes so I’ll have to use screenshots instead of a live demo. Any chance this could be done by Wednesday or Thursday? I need to send them slides in advance.

**Comment by htpvu** [comment]
By end of Wednesday it is.

**Comment by karenhanson** [comment]
I have deleted them, will close once confirmed

**Comment by karenhanson** [comment]
Done!

**Comment by sayeedmd** [comment]
Perfect. Thanks.
