### ISSUE TITLE
Investigate an approach for dealing with updating indexer's mapping during the data migration process

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/general-issues#57]
@karenhanson will test out a couple of options using pass-docker set up to decide which course of action we should take in updating indexer mapping. This will inform and solidify data migration plan for the releaes of Proxy Submitter feature

Outcome should include a detailed proposal of how we should carry out this update in demo and production envs.

**Comment by karenhanson** [comment]
Have documented how to do the migration
