### ISSUE TITLE
Update the OA-PASS code base to add separate fields of submitter's name and submitter's email to Submission object

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/general-issues#58]
We discovered that the `Submission`'s `submitter` field cannot point to both URI of a `User` object and URI of and email address - a limitation of Ember data. So to capture the information of non-`User` submitter, we need to take an alternative approach by adding separate fields for the submitter's name and email address.

In doing so, the following tasks need to be performed. 

- [x] Update model in pass-data-model, including READMEs and documentation.
- [x] Update fcrepo image in pass-docker
- [x] Update pass-indexer
- [x] Release pass-indexer
- [x] Update the PASS java client
- [x] Release the PASS java client
- [x] Update indexer image in pass-docker
- [x] Updating birkland/assets mappings
- [x] PR for pass-docker changes (latest fcrepo, indexer, assets)

Updating of Notification Service and Ember UI to pick up this change will be accounted for in different tickets. Other components will be updated in a different round of updates as not to block the critical path of Proxy Submitter feature integration.

**Comment by karenhanson** [comment]
Done
