### ISSUE TITLE
Need testing of https://test.pass.library.jhu.edu

### ISSUE THREAD

**Issue by derekbelrose** [OA-PASS/general-issues#60]
We need some people to test the Test environment.  Any user who has an account in Demo should be able to test this as well.

Once this is done and confirmed, we can migrated Demo to the new deployment scheme.

**Comment by htpvu** [comment]
I found an issue, in which the deposit agreement box is empty. NOt sure about the cause. this data comes from the repository object in fcrepo. i looked at the repository object itself, it seems to have the correct value. not sure why it's not showing up here. here's link to the object in fedora https://test.pass.library.jhu.edu/fcrepo/rest/repositories/41/96/0a/92/41960a92-d3f8-4616-86a6-9e9cadc1a269

![screen shot 2018-10-31 at 1 33 03 pm](https://user-images.githubusercontent.com/11050142/47807167-cc812b80-dd11-11e8-93fb-d9d86dbd7641.png)

**Comment by derekbelrose** [comment]
Hanh,

Can you, maybe, explain briefly how ember gets this data?  Does it literally just contact fedora and grab the data?  Is there access to one of the UI developers who might be able to explain why this might be happening?

On Oct 31, 2018, at 1:50 PM, Hanh Vu <notifications@github.com<mailto:notifications@github.com>> wrote:


I found an issue, in which the deposit agreement box is empty. NOt sure about the cause. this data comes from the repository object in fcrepo. i looked at the repository object itself, it seems to have the correct value. not sure why it's not showing up here. here's link to the object in fedora https://test.pass.library.jhu.edu/fcrepo/rest/repositories/41/96/0a/92/41960a92-d3f8-4616-86a6-9e9cadc1a269

[screen shot 2018-10-31 at 1 33 03 pm]<https://user-images.githubusercontent.com/11050142/47807167-cc812b80-dd11-11e8-93fb-d9d86dbd7641.png>

This behavior does not exist in demo.

I was still able to submit the submission.

**Comment by htpvu** [comment]
I’ll look into this with you today.

Hanh Vu
Project Manager, Data Conservancy
Sheridan Library, Johns Hopkins University



On Wed, Oct 31, 2018 at 5:36 PM -0400, "derekbelrose" <notifications@github.com<mailto:notifications@github.com>> wrote:

Hanh,

Can you, maybe, explain briefly how ember gets this data? Does it literally just contact fedora and grab the data? Is there access to one of the UI developers who might be able to explain why this might be happening?

On Oct 31, 2018, at 1:50 PM, Hanh Vu <notifications@github.com<mailto:notifications@github.com>> wrote:


I found an issue, in which the deposit agreement box is empty. NOt sure about the cause. this data comes from the repository object in fcrepo. i looked at the repository object itself, it seems to have the correct value. not sure why it's not showing up here. here's link to the object in fedora https://test.pass.library.jhu.edu/fcrepo/rest/repositories/41/96/0a/92/41960a92-d3f8-4616-86a6-9e9cadc1a269

[screen shot 2018-10-31 at 1 33 03 pm]<https://user-images.githubusercontent.com/11050142/47807167-cc812b80-dd11-11e8-93fb-d9d86dbd7641.png>

This behavior does not exist in demo.

I was still able to submit the submission.

**Comment by derekbelrose** [comment]
Ok to further complicate this issue,

If you don't use the 'abc' doi and, instead, leave it empty it populates that field in the Ember application.

![image](https://user-images.githubusercontent.com/237629/47855201-4a007680-ddba-11e8-8953-68f4bb54dc48.png)

**Comment by derekbelrose** [comment]
Thanks @jrmartino.  At this point, I don't know where the ember application gets this deposit agreement. It's also confusing because it works if you don't specify a DOI.  Can we test with a different DOI?  Is that possible?

**Comment by htpvu** [comment]
@derekbelrose i've tested with a variety of DOIs. 

Here are a few you can try. any of the format works. 
https://doi.org/10.1016/j.polymer.2013.10.051 
https://doi.org/10.1016/j.polymer.2014.12.057
10.1039/C7SM01695F

**Comment by derekbelrose** [comment]
There was a discrepancy between the versions of Ember and FCrepo running on Demo and Test.  I aligned those versions and updated the stack.

Hanh is testing again.

**Comment by derekbelrose** [comment]
All manual tests seem to have passed.
