### ISSUE TITLE
Please test new deployment of Pass-Demo

### ISSUE THREAD

**Issue by derekbelrose** [OA-PASS/general-issues#63]
Please test the new deployment of PASS-Demo.  It should be exactly like the old environment, but it's on the new deployment process.

demo is at https://demo.pass.library.jhu.edu/

**Comment by jrmartino** [comment]
workflow seems fine as usual. the only thing i'd mention is a usability thing - i may have my text size set to something larger than the defailt - as a result, the SubmittedDate has a weird line wrap: 
11/01/201
8

**Comment by derekbelrose** [comment]
That’s not a product of the deployment, though. Right?

**Comment by htpvu** [comment]
This looks fine to me Demo. Font size looks normal as well. I wonder if Jim had his browser zoomed in. in any case, indeed not a deployment issue.
