### ISSUE TITLE
Redeploy Production using Terraform

### ISSUE THREAD

**Issue by derekbelrose** [OA-PASS/general-issues#64]

**Comment by derekbelrose** [comment]
- [ ] dump PostgreSQL database
- [ ] sync s3 bucket
- [ ] snapshot elastic search
- [ ] deploy production environment with terraform
- [ ] restore elastic search snapshot
- [ ] restore PostgreSQL database
- [ ] sync s3 bucket up to new environment
- [ ] Initial testing by operations
- [ ] announce for testing
- [ ] shut down original environment

**Comment by htpvu** [comment]
@derekbelrose is this done?

**Comment by derekbelrose** [comment]
Yes
