### ISSUE TITLE
Deploy Proxy Submitter feature to TEST

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/general-issues#66]
new images:
fcrepo: `image: oapass/fcrepo:4.7.5-3.2-2`
ember: `image: oapass/ember:20181108-8c1a4a3`
static-html: `image: oapass/static-html:20181101-c7be0f8`
indexer: `image: oapass/indexer:0.0.17-3.2-SNAPSHOT`
deposit: `image: oapass/deposit-services:0.1.0-3.2`
authz: `image: oapass/authz:0.4.0-3.2`
notification: `oapass/notification-services:0.0.2-3.2@sha256:7a693ce4005c88bdf93104d1cea1caec569dbb994ad8eaa07150dcd815a0e002` - configurations for notification service are described here: https://github.com/OA-PASS/pass-docker/tree/model-3.0#notification-services-environment

(i'm not sure if elastic search needs updated?)

Here's the migration plan as we planned in theory before https://docs.google.com/document/d/1XYkA6spS_QRUAU6ToLhlQb2u6UoWsw9Qx16aILrSDfA/edit#heading=h.g573llsxb65i

**Comment by derekbelrose** [comment]
This is done.
