### ISSUE TITLE
Analyze the requirements for notification service and design a plan for its implementation as it relates to the Proxy Submitter usecase

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/general-issues#7]
expected outcomes: 
- A description the need that notification service is trying to address at this use case 
- enumerate its components and specify its interaction with existing components in PASS (what resources does it act on, using which criteria, how does it communicate with other things) 
- enumerate list of tasks that will need to be done in order to implement this tool. (as high/low of a level as you can. we'll follow up when i get back)

**Comment by emetsger** [comment]
Current design document (still in-progress) available [here](https://docs.google.com/document/d/1k8mIM3Z6k7yx3D0LYuyT4LNMLVELIg4AuMAJw-OM3GQ/edit?usp=sharing)

**Comment by emetsger** [comment]
Task list available [here](https://docs.google.com/spreadsheets/d/1LyJC-ZSLVC1G0vkw6PQyr9e9i5FM8YqRA1VXdXhpM-8/edit#gid=0)

**Comment by htpvu** [comment]
The high level plan for implementation is set. Other design feedback will be addressed in this card: https://github.com/OA-PASS/notification-services/issues/5
