### ISSUE TITLE
Deploy Proxy-submitter to DEMO env

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/general-issues#70]
**new images:**
- [x] fcrepo: `image: oapass/fcrepo:4.7.5-3.2-3@sha256:b7036b1f61d84341aea1b198ed91ecd69af387a9336e76233e463713b105b05c`

- [x] ember: `image: oapass/ember:20181113-be78916@sha256:42643d501f2e451cc2eb58e5e809523e7342e6582e1f8c541b4ed0307055e3e1`

- [x] static-html: `image: oapass/static-html:20181101-c7be0f8@sha256:38e3098807e250141d5efd4a3db511e248932353d29d887b4c6dd789725447c4`

- [x] indexer: `image: oapass/indexer:0.0.17-3.2-SNAPSHOT@sha256:b572bb48814fb1624a29556fd648de7b4f432c9f65f904d609efcf7f8ac36948`

 
- [x] deposit: `iimage: oapass/deposit-services:0.1.0-3.2-1@sha256:fbe0f70af890ab97a0b2ab6c8d3ad058f7117d81c029b0a1980d037e9a7adc33`
**Note**: the `file:/repositories.json` file was newly updated as of 11/14.

- [ ] authz: `image: oapass/authz:0.4.0-3.2@sha256:64a5a8e7a4280d990d91ca60dffefbde4ad967547569d13d71e6e0d1aed32492`

- [x] notification: `oapass/notification-services:0.0.2-3.2@sha256:7a693ce4005c88bdf93104d1cea1caec569dbb994ad8eaa07150dcd815a0e002` - configurations for notification service are described here: https://github.com/OA-PASS/pass-docker/tree/model-3.0#notification-services-environment

 
Here's the migration plan as we planned in theory before https://docs.google.com/document/d/1XYkA6spS_QRUAU6ToLhlQb2u6UoWsw9Qx16aILrSDfA/edit#heading=h.g573llsxb65i

**Comment by derekbelrose** [comment]
Notification service deployed.
Authz is forthcoming

**Comment by derekbelrose** [comment]
All containers deployed, authz is running.

Closing ticket as it will be done in several hours.

**Comment by derekbelrose** [comment]
authz completed this weekend.  This is 100% complete.
