### ISSUE TITLE
deploy new ember image to TEST (20181115-37cab27)

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/general-issues#73]
`image: oapass/ember:20181115-37cab27@sha256:18bbff8f018df480af12a0abcfed3cde9afb9dcd6f5a9779bb57d9bd70ea7b70`

**Comment by derekbelrose** [comment]
This has been deployed.

Should I wait until this is tested as working before we deploy to demo?

**Comment by htpvu** [comment]
We're focusing our testing effort in demo, so I would deploy this to demo right away so folks can continue to testing in demo. 

AFter the launch we should figure out how to effectively make user of the 3 envs set up. :)

**Comment by htpvu** [comment]
Done
