### ISSUE TITLE
Deploy ember image version 20181116-5ef9fa4 to TEST and DEMO

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/general-issues#75]
ember: `image: oapass/ember:20181116-5ef9fa4@sha256:18c9d14c6d5edeea7e008109521f6c87823ab38ee968a9f81c44b396cc412fc7`

static-html: `image: oapass/static-html:20181116-4ab9eb3@sha256:2c5a8f315783ab41205aaead6c82c6148f9d6334b1dc33b7bf31033cf008d2d6` 

Please deploy the above images for testing by Monday (11/19) morning at the latest. Or earlier if that works better.

**Comment by htpvu** [comment]
Please close the ticket when this is done.

**Comment by derekbelrose** [comment]
These have been deployed to Test

They will be deployed to Demo once I can restart it.

**Comment by derekbelrose** [comment]
Deployed to Demo.
