### ISSUE TITLE
Enable visitor of pass.jhu.edu to see a user friendly message during the Proxy Submitter feature migration window. 

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/general-issues#78]
Ideally, the static and public pages would be available to the public during migration. Only when user logs in that he/she shown the under construction message. But if that's too much given the timeframe, taking PASS completely offline would be fine. 

I think the work would at least include:
- (For Karen) creation of a themed and static html page with appropriate message to be shown to visitor 
-- The message should include the time estimate as to when PASS will be back online
- (For Derek) some magic that would show user the above page at the opportune time (either when they visit pass.jhu.edu or when they get to pass.jhu.edu/app) depending on how complicate this is to implement.

**Comment by derekbelrose** [comment]
Hmm.  This is very difficult as the infrastructure completely goes down.  I can bring up a new docker service to serve a single web page.

This will work for https://pass.jhu.edu and all under it.  I just need the assets from @karenhanson

**Comment by htpvu** [comment]
@derekbelrose as I mentioned in the plan for next week, we can launch without this being implemented, if it proves to be too much for the time frame.

**Comment by derekbelrose** [comment]
I understand, but I do think it is important to have regardless.  If I have time, I want to implement this functionality for downtime, updates, etc.
