### ISSUE TITLE
Deploy new ember image to test (resolves userToken issue #85)

### ISSUE THREAD

**Issue by karenhanson** [OA-PASS/general-issues#89]
Here is a new version of ember to be deployed to `test` for testing. This should fix the userToken issue documented in #85 and restore the new user fields.

`oapass/ember:20181127-aec1ef8@sha256:7365cc4b1149907cfbfeb4bcad678b5146dc6c28ab025d94d09bb889759d1ed5`

**Comment by htpvu** [comment]
done
