### ISSUE TITLE
Deploy new user invite feature in PROD and DEMO

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/general-issues#90]
This should fix the userToken issue documented in #85 and restore the new user fields.

`oapass/ember:20181127-aec1ef8@sha256:7365cc4b1149907cfbfeb4bcad678b5146dc6c28ab025d94d09bb889759d1ed5`

This can be done in the off hours.

**Comment by derekbelrose** [comment]
This has been completed on both DEMO and PROD
