### ISSUE TITLE
Explore Ember's behavior when a new repository with new formSchema is put into the system to be rendered.

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/general-issues#92]
This is an exercise to help us figure out how to make metadata capturing more configurable based on repositories' differing requirements.

**Comment by htpvu** [comment]
@karenhanson i believe this is done, please link to the document you created and close this ticket. thank you.

**Comment by karenhanson** [comment]
Here is the document exploring the behavior:
https://docs.google.com/document/d/10TZY5vt6ET6CtAMoZ5U1_6bGDcrKsl4b-qunc4bJFT8
