### ISSUE TITLE
GitHub Issues clean up 

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/general-issues#94]
Please review the github repos you are familiar with and close out tickets that are no longer relevant or have been fixed. 

Take notes of important ones that  you think  we will HAVE to work on during this development cycle (first half of 2019)

**Comment by jrmartino** [comment]
all of the tickets assigned to me have to do with the suspended NIHMS status feature - i hav commented on these, can reclassify  them if needed

**Comment by htpvu** [comment]
Tickets are closed or commented on appropriately. All Open tickets are relevant.
