### ISSUE TITLE
Vulnerability in pass-authz with jackson-databind

### ISSUE THREAD

**Issue by derekbelrose** [OA-PASS/general-issues#95]
Please take a look at this and determine if an update of the library is warranted:

https://github.com/OA-PASS/pass-authz/network/alert/pom.xml/com.fasterxml.jackson.core:jackson-databind/open

**Comment by birkland** [comment]
This was resolved in https://github.com/OA-PASS/pass-authz/commit/8f0cbc5c568b9bbe5eec2b1f78d762dc5ba3e49d
